clear
T=load('TMEV.DAT');
del_ls=load('DELTA_LS.DAT');
fpi=load('FPI.DAT');
Zphi=load('ZPHI.DAT');
fpiA=load('../../Tc0_137IA/BUFFER/FPI.DAT');
ZphiA=load('../../Tc0_137IA/BUFFER/ZPHI.DAT');
sigma=fpi./Zphi.^(1/2);
sigmaA=fpiA./ZphiA.^(1/2);
chi=sigmaA-sigma;
ddeldT=del_ls(2:end)-del_ls(1:end-1);
dsigmsdT=sigma(2:end)-sigma(1:end-1);
dchidT=chi(2:end)-chi(1:end-1);
Tmid=(T(2:end)+T(1:end-1))/2;
plot(T,chi)