SUBROUTINE GAPEQ(N, X, FVEC)

  USE GAPPARA
  IMPLICIT NONE

  INTEGER,INTENT(IN) :: N
  REAL(16),INTENT(IN)  :: X(N)
  REAL(16),INTENT(OUT) :: FVEC(N)
  REAL(16) :: RHO

  RHO=X(1)

  FVEC(1)=LAM(2) - JL/(SQRT(2.Q+0)*SQRT(RHO)) + LAM(3)*(-KAPPA + RHO) + &
        (LAM(4)*(-KAPPA + RHO)**2)/2.Q+0 + (LAM(5)*(-KAPPA + RHO)**3)/6.Q+0 + &
        (LAM(6)*(-KAPPA + RHO)**4)/24.Q+0

END
SUBROUTINE GAPEQS(N, X, FVEC)
  USE GAPPARA
  IMPLICIT NONE
  INTEGER,INTENT(IN) :: N
  REAL(16),INTENT(IN)  :: X(N)
  REAL(16),INTENT(OUT) :: FVEC(N)
  REAL(16) :: RHO,RHOS
  REAL(16) :: DRHO1V_S

  RHOS=X(1)
  RHO=2.Q+0*RHOS

  DRHO1V_S=LAM(2) + LAM(3)*(-KAPPA + RHO) +  &
        (LAM(4)*(-KAPPA + RHO)**2)/2.Q+0 + (LAM(5)*(-KAPPA + RHO)**3)/6.Q+0 + &
        (LAM(6)*(-KAPPA + RHO)**4)/24.Q+0
  FVEC=SQRT(2.Q+0)*sqrt(2.Q+0*RHOS)*DRHO1V_S-C_BAR_S
END SUBROUTINE GAPEQS
