PROGRAM EQCD
!Rui Wen 2020.12.30

  USE CONST_SAVE , ONLY : PI
  USE TMU_MOD
  USE PHYVAR_MOD
  USE RHOS_COM
  USE SELFEQ_MOD
  
  IMPLICIT NONE
  REAL(16) :: L,LB 
  !POLYAKOV LOOP
  REAL(16) :: VTOTAL
  REAL(16),PARAMETER :: DT   =  1.Q+0
  REAL(16),PARAMETER :: MUBI =  0.Q+0
  REAL(16),PARAMETER :: MU_UP=  0.Q+0
  REAL(16),PARAMETER :: MU_DOWN=-MU_UP
  REAL(16) :: MUDELTA,MUB
  REAL(16) :: L_I1,L_I2,LB_I1,LB_I2
  INTEGER(2) :: I,J
  INTEGER(2),PARAMETER :: ITMAX=0
  INTEGER(2),PARAMETER :: MUNUM= 31
  REAL(16),PARAMETER :: MUNUM_R=REAL(MUNUM,KIND=16)
  REAL(16) :: L_SAVE(200)

  RHOS_I=126.Q+0**2/2.Q+0

  CALL GAUSSMOD_CAL()
  CALL Y1W1MOD_CAL()

  L_I1=1.Q-10
  LB_I1=1.Q-10

  L_I2=L_I1
  LB_I2=LB_I1


  MUDELTA=0.Q+0

  DO I=1,250
    T=1.Q+00*REAL(I,KIND=16)
    JL_UV=3.38Q+9
    MUB=MUBI
    MU=MUB/3.Q+0

    CALL SELFEQ(L_I1,LB_I1,L,LB,VTOTAL)
    L_I1=2.Q+0*L-L_I2
    L_I2=L
    LB_I1=2.Q+0*LB-LB_I2
    LB_I2=LB

    WRITE(*,"('I=', I4)")I
    WRITE(*,*)'L =',L
    WRITE(*,*)'LB=',LB
    WRITE(*,"('MUB_MEV=', F15.7, T25, 'T_MEV=', F15.7)")MUB,T
    WRITE(*,*)'MF:',REAL(MF,KIND=8),'MFS',REAL(MFS,KIND=8)
    WRITE(*,*)'MPI_PHY:',MPION_PHY
    WRITE(*,*)'MSG_PHY:',MSIGMA_PHY

    OPEN(UNIT=51,FILE='./BUFFER/TMEV.DAT',POSITION='APPEND')
    WRITE(51,*)T
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/MUB.DAT',POSITION='APPEND')
    WRITE(51,*)MUB
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/L.DAT',POSITION='APPEND')
    WRITE(51,*)L
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/LB.DAT',POSITION='APPEND')
    WRITE(51,*)LB
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/MF.DAT',POSITION='APPEND')
    WRITE(51,*)MF
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/MFS.DAT',POSITION='APPEND')
    WRITE(51,*)MFS
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/VTOTAL.DAT',POSITION='APPEND')
    WRITE(51,*)VTOTAL
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/H.DAT',POSITION='APPEND')
    WRITE(51,*)H
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/ZPHI.DAT',POSITION='APPEND')
    WRITE(51,*)ZPHI
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/ZPSI.DAT',POSITION='APPEND')
    WRITE(51,*)ZPSI
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/ZA.DAT',POSITION='APPEND')
    WRITE(51,*)ZA
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/G.DAT',POSITION='APPEND')
    WRITE(51,*)G
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/MPION_PHY.DAT',POSITION='APPEND')
    WRITE(51,*)MPION_PHY
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/MSIGMA_PHY.DAT',POSITION='APPEND')
    WRITE(51,*)MSIGMA_PHY
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/MPION.DAT',POSITION='APPEND')
    WRITE(51,*)MPION
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/MSIGMA.DAT',POSITION='APPEND')
    WRITE(51,*)MSIGMA
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/LAMIR_1.DAT',POSITION='APPEND')
    WRITE(51,*)LAMIR_1
    CLOSE(51)
    OPEN(UNIT=51,FILE='./BUFFER/LAMIR_2.DAT',POSITION='APPEND')
    WRITE(51,*)LAMIR_2
    CLOSE(51)
    OPEN(UNIT=51,FILE='./BUFFER/LAMIR_3.DAT',POSITION='APPEND')
    WRITE(51,*)LAMIR_3
    CLOSE(51)
    OPEN(UNIT=51,FILE='./BUFFER/LAMIR_4.DAT',POSITION='APPEND')
    WRITE(51,*)LAMIR_4
    CLOSE(51)
    OPEN(UNIT=51,FILE='./BUFFER/LAMIR_5.DAT',POSITION='APPEND')
    WRITE(51,*)LAMIR_5
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/FPI.DAT',POSITION='APPEND')
    WRITE(51,*)FPI
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/C.DAT',POSITION='APPEND')
    WRITE(51,*)CL
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/DELTA_LS.DAT',POSITION='APPEND')
    WRITE(51,*)DELTA_LS
    CLOSE(51)

    OPEN(UNIT=51,FILE='./BUFFER/DRHO1V.DAT',POSITION='APPEND')
    WRITE(51,*)REAL(DRHO1V,KIND=8),REAL(DRHO1V_S,KIND=8)
    CLOSE(51)
  END DO
END PROGRAM EQCD
