MODULE INTLIN_MOD
!Rui Wen 2020.12.30
CONTAINS
SUBROUTINE INTLIN(X_BEF,Y_BEF,X_AFT,Y_AFT)

  IMPLICIT NONE

  REAL(16),INTENT(IN)  :: X_BEF(:),Y_BEF(:),X_AFT(:)
  REAL(16),INTENT(OUT) :: Y_AFT(:) 
  REAL(16) X
  INTEGER(2) :: KOUNT,NPOINT
  INTEGER(2) :: I,J,J_INI
  INTEGER(2) :: J1,J2

  KOUNT=SIZE(X_BEF)
  NPOINT=SIZE(X_AFT)

  J_INI=1

  DO I=1, NPOINT
    X=X_AFT(I)
    DO J=J_INI, KOUNT
      J1=J
      IF(J1<KOUNT)THEN
        J2=J1+1
        IF(X_BEF(J2)<=X)THEN
          Y_AFT(I)=(X-X_BEF(J1))/(X_BEF(J2)-X_BEF(J1))*(Y_BEF(J2)-Y_BEF(J1))+Y_BEF(J1)
          EXIT
        END IF
      ELSE
        Y_AFT(I)=Y_BEF(J1)
        EXIT
      END IF
    END DO
    J_INI=J1
  END DO

END SUBROUTINE INTLIN
END MODULE INTLIN_MOD
