MODULE FNF_MOD_8
CONTAINS
SUBROUTINE FNF012_8(X,T,L,LB,NF0,NF1,NF2)
  !FERMION DISTRIBUTION FUNCTION

  IMPLICIT NONE

  REAL(16),INTENT(IN) :: X,T,L,LB
  REAL(16),INTENT(OUT) :: NF0,NF1,NF2
  REAL(16) :: OVER

  OVER=X/T
  IF(OVER > 60.Q+0)THEN
    NF0=0.Q+0
    NF1=0.Q+0
    NF2=0.Q+0
  ELSE
    NF0=1.Q+0/(1.Q+0+3.Q+0*LB*EXP(X/T)+3.Q+0*L*EXP(2.Q+0*X/T)+EXP(3.Q+0*X/T))
    NF1=(2*EXP(X/T))/(1.Q+0+3.Q+0*LB*EXP(X/T)+3.Q+0*L*EXP(2.Q+0*X/T)+EXP(3.Q+0*X/T))
    NF2=(EXP(2.Q+0*X/T))/(1.Q+0+3.Q+0*LB*EXP(X/T)+3.Q+0*L*EXP(2.Q+0*X/T)+EXP(3.Q+0*X/T))
  END IF
END SUBROUTINE FNF012_8
END MODULE FNF_MOD_8

MODULE INT_QUATKLOOP_MOD
!Rui Wen 2021.01.18
CONTAINS
SUBROUTINE INT_QUATKLOOP(CHANGE,K16,T16,MU16,L16,LB16,MF2_16,NFFDNX,NFADNX,F2A_16,F3A_16,FQL0,FQL1,FQLPHI0,FQLPHI1)
  
  USE OMP_LIB

  USE THRNUM_MOD
  USE GAUSSMOD

  USE FNF_MOD_8
  IMPLICIT NONE

  LOGICAL,INTENT(IN)   :: CHANGE
  REAL(16),INTENT(IN)  :: K16,T16,MU16,L16,LB16
  REAL(16),INTENT(IN)  :: MF2_16
  REAL(16),INTENT(IN)  :: NFFDNX(6),NFADNX(6)
  REAL(16),INTENT(IN)  :: F2A_16,F3A_16
  REAL(16),INTENT(OUT) :: FQL0,FQL1,FQLPHI0,FQLPHI1
  REAL(16) :: NFF,NFD1XF,NFD2XF,NFA,NFD1XA,NFD2XA
  REAL(16) :: EQ0
  REAL(16) :: K2
  REAL(16) :: F1F1_Q0,F2F1_Q0
  REAL(16) :: F1F1PHI_Q0,F2F1PHI_Q0
  REAL(16) :: FDNF1_Q0,FDNF2_Q0,FDNF1D1_Q0,FDNF2D1_Q0
  REAL(16) :: Q(N_X),COSTHE(N_CTH,N_X)
  REAL(16) :: Q2_QMP(N_X),EQMP(N_X)
  REAL(16) :: X(N_X),NF0(N_X),NF1(N_X),NF2(N_X)
  REAL(16) :: NFFQMP(N_X),NFAQMP(N_X)
  REAL(16) :: FDNF1(N_X),FDNF2(N_X),FDNF1D1(N_X),FDNF2D1(N_X)
  REAL(16) :: F1F1(N_CTH,N_X),F2F1(N_CTH,N_X)
  REAL(16) :: F1F1PHI(N_CTH,N_X),F2F1PHI(N_CTH,N_X)
  REAL(16) :: FQL0IX(N_X),FQL1IX(N_X),FQLPHI0IX(N_X),FQLPHI1IX(N_X)
  REAL(16) :: CTHINTE_QLIX(N_X),CTHINTE_QL_PHIIX(N_X)
  REAL(16) :: XPRIMEIX(N_X),RF_PLUS(N_X)

  REAL(16) :: K,T,MU,L,LB
  REAL(16) :: MF2
  REAL(16) :: F2A,F3A
  INTEGER(2) :: I_X,I_CTH

  NFF   =REAL(NFFDNX(1),KIND=16)
  NFD1XF=REAL(NFFDNX(2),KIND=16)
  NFD2XF=REAL(NFFDNX(3),KIND=16)
  NFA   =REAL(NFADNX(1),KIND=16)
  NFD1XA=REAL(NFADNX(2),KIND=16)
  NFD2XA=REAL(NFADNX(3),KIND=16)

  K =REAL(K16 ,KIND=16)
  T =REAL(T16 ,KIND=16)
  MU=REAL(MU16,KIND=16)
  L =REAL(L16 ,KIND=16)
  LB=REAL(LB16,KIND=16)
  MF2=REAL(MF2_16,KIND=16)

  F2A=REAL(F2A_16,KIND=16)
  F3A=REAL(F3A_16,KIND=16)

  EQ0=K*SQRT(1.Q+0 + MF2)
  K2=K**2

  FDNF1_Q0=NFD1XA
  FDNF2_Q0=NFD1XF
  FDNF1D1_Q0=(K2*NFD2XA)/(4.Q+0*EQ0)
  FDNF2D1_Q0=(K2*NFD2XF)/(4.Q+0*EQ0)

  F1F1_Q0=(K**3*(FDNF1_Q0 + FDNF2_Q0 - (NFA + NFF)/(EQ0 + EQ0)                 &
      - (NFA + NFF)/(EQ0 + EQ0)))/(4.Q+0*EQ0**2)

  F2F1_Q0=(K**5*(FDNF1_Q0 + FDNF2_Q0 - (NFA + NFF)/(EQ0 + EQ0) +               &
      - (NFA + NFF)/(EQ0 + EQ0)))/(8.Q+0*EQ0**4) -                             &
      (K**3*(FDNF1D1_Q0 + FDNF2D1_Q0 + (K2*NFD1XA)/(2.Q+0*EQ0*(-EQ0 - EQ0)) -  &
      (K2*NFD1XF)/(2.Q+0*EQ0*(EQ0 + EQ0)) -                                    &
      (K2*(- NFA - NFF))/(2.Q+0*EQ0*(EQ0 + EQ0)**2) +                          &
      (K2*(NFA + NFF))/(2.Q+0*EQ0*(-EQ0 - EQ0)**2)))/(4.Q+0*EQ0*EQ0)

  IF (CHANGE .EQV. .TRUE.) THEN
    F1F1PHI_Q0=F1F1_Q0
    F2F1PHI_Q0=F2F1_Q0
  END IF

  !$OMP PARALLEL DO NUM_THREADS(NTHR) PRIVATE(I_CTH)
  DO I_X=1,N_X
    Q(I_X)=K*SQRT_Y_X(I_X)
    CTHINTE_QLIX(I_X)=0.Q+0
    CTHINTE_QL_PHIIX(I_X)=0.Q+0
    COSTHE(:,I_X)=Y_CTH
    DO I_CTH=1,N_CTH
      Q2_QMP(I_X)=Q(I_X)**2+K2-2.Q+00*Q(I_X)*K*COSTHE(I_CTH,I_X)
      IF(Q2_QMP(I_X)<K2)THEN
        EQMP(I_X)=EQ0
      ELSE
        EQMP(I_X)=SQRT(Q2_QMP(I_X)+K2*MF2)
      END IF

      IF(ABS(EQ0 - EQMP(I_X))/EQ0<1.Q-7)THEN
        F1F1(I_CTH,I_X)=F1F1_Q0
        F2F1(I_CTH,I_X)=F2F1_Q0
        F1F1PHI(I_CTH,I_X)=F1F1PHI_Q0
        F2F1PHI(I_CTH,I_X)=F2F1PHI_Q0
      ELSE
        X(I_X)=EQMP(I_X)-MU
        CALL FNF012_8(X(I_X),T,L,LB,NF0(I_X),NF1(I_X),NF2(I_X))
        NFFQMP(I_X)=NF0(I_X)+LB*NF1(I_X) + L*NF2(I_X)

        X(I_X)=EQMP(I_X)+MU
        CALL FNF012_8(X(I_X),T,LB,L,NF0(I_X),NF1(I_X),NF2(I_X))
        NFAQMP(I_X)=NF0(I_X) + L*NF1(I_X) + LB*NF2(I_X)

        FDNF1(I_X)=(-NFA + NFAQMP(I_X))/(-EQ0 + EQMP(I_X))
        FDNF2(I_X)=(NFF - NFFQMP(I_X))/(EQ0 - EQMP(I_X))
        FDNF1D1(I_X)=(K2*(-NFA + NFAQMP(I_X)))/(2.Q+0*EQ0*(-EQ0 + EQMP(I_X))**2) - &
           (K2*NFD1XA)/(2.Q+0*EQ0*(-EQ0 + EQMP(I_X)))
        FDNF2D1(I_X)=(K2*NFD1XF)/(2.Q+0*EQ0*(EQ0 - EQMP(I_X))) -                   &
           (K2*(NFF - NFFQMP(I_X)))/(2.Q+0*EQ0*(EQ0 - EQMP(I_X))**2)

        F1F1(I_CTH,I_X)=(K**3*(FDNF1(I_X)+FDNF2(I_X) + (- NFAQMP(I_X)-NFF)/(EQ0+EQMP(I_X)) + &
           (NFA + NFFQMP(I_X))/(-EQ0-EQMP(I_X))))/(4.Q+0*EQ0*EQMP(I_X))

        F2F1(I_CTH,I_X)=(K**5*(FDNF1(I_X)+FDNF2(I_X) + (- NFAQMP(I_X)-NFF)/(EQ0+EQMP(I_X)) + &
           (NFA + NFFQMP(I_X))/(-EQ0- EQMP(I_X))))/(8.Q+0*EQ0**3*EQMP(I_X)) -                &
           (K**3*(FDNF1D1(I_X) + FDNF2D1(I_X) + (K2*NFD1XA)/(2.Q+0*EQ0*(-EQ0 - EQMP(I_X))) - &
           (K2*NFD1XF)/(2.Q+0*EQ0*(EQ0 + EQMP(I_X))) -                                     &
           (K2*(- NFAQMP(I_X) - NFF))/(2.Q+0*EQ0*(EQ0 + EQMP(I_X))**2) +                      &
           (K2*(NFA + NFFQMP(I_X)))/(2.Q+0*EQ0*(-EQ0 - EQMP(I_X))**2)))/(4.Q+0*EQ0*EQMP(I_X))

        IF (CHANGE .EQV. .TRUE.) THEN
          F1F1PHI(I_CTH,I_X)=F1F1(I_CTH,I_X)
          F2F1PHI(I_CTH,I_X)=F2F1(I_CTH,I_X)
        END IF
      END IF
      XPRIMEIX(I_X)=Y_X(I_X)+1.Q+0-2.Q+0*SQRT_Y_X(I_X)*COSTHE(I_CTH,I_X)
      IF(XPRIMEIX(I_X)<1.Q+0)THEN
        RF_PLUS(I_X)=1.Q+0/SQRT(XPRIMEIX(I_X))
      ELSE
        RF_PLUS(I_X)=1.Q+0
      END IF
      CTHINTE_QLIX(I_X)=CTHINTE_QLIX(I_X)+W_CTH(I_CTH)*((F1F1(I_CTH,I_X)-F2F1(I_CTH,I_X))    &
        +(SQRT_Y_X(I_X)*COSTHE(I_CTH,I_X)**2-COSTHE(I_CTH,I_X))*RF_PLUS(I_X)*(F2F1(I_CTH,I_X)&
        -F1F1(I_CTH,I_X)/2.Q+0))
      IF (CHANGE .EQV. .TRUE.) THEN
        CTHINTE_QL_PHIIX(I_X)=CTHINTE_QL_PHIIX(I_X)+W_CTH(I_CTH)*(((F1F1PHI(I_CTH,I_X)-F2A)-(F2F1PHI(I_CTH,I_X)-F3A)) &
         +((SQRT_Y_X(I_X)-COSTHE(I_CTH,I_X))*RF_PLUS(I_X)*F2F1PHI(I_CTH,I_X)-F3A)-1.Q+0/2.Q+0*((SQRT_Y_X(I_X)  &
         -COSTHE(I_CTH,I_X))*RF_PLUS(I_X)*F1F1PHI(I_CTH,I_X)-F2A))
      END IF
    END DO
    FQL0IX(I_X)=W_X(I_X)*SQRT_Y_X(I_X)*CTHINTE_QLIX(I_X)
    FQL1IX(I_X)=W_X(I_X)*Y_X(I_X)*CTHINTE_QLIX(I_X)
    IF (CHANGE .EQV. .TRUE.) THEN
      FQLPHI0IX(I_X)=W_X(I_X)*SQRT_Y_X(I_X)*CTHINTE_QL_PHIIX(I_X)
      FQLPHI1IX(I_X)=W_X(I_X)*Y_X(I_X)*CTHINTE_QL_PHIIX(I_X)
    END IF
  END DO
  !$OMP END PARALLEL DO
  FQL0=REAL(SUM(FQL0IX),KIND=16)
  FQL1=REAL(SUM(FQL1IX),KIND=16)
  IF (CHANGE .EQV. .TRUE.) THEN
    FQLPHI0=REAL(SUM(FQLPHI0IX),KIND=16)
    FQLPHI1=REAL(SUM(FQLPHI1IX),KIND=16)
  END IF
END SUBROUTINE INT_QUATKLOOP
END MODULE INT_QUATKLOOP_MOD
