!Rui Wen 2020.12.19

MODULE THRNUM_MOD
  IMPLICIT NONE
  SAVE
  INTEGER(2),PARAMETER :: NTHR=2
END MODULE THRNUM_MOD
  
MODULE CONST_SAVE
  IMPLICIT NONE
  SAVE
  REAL(16),PARAMETER :: PI=3.141592653589793238462643383279Q+0
  REAL(16),PARAMETER :: NC=3.Q+0
  REAL(16),PARAMETER :: NF=2.Q+0
  REAL(16),PARAMETER :: V3=1.Q+0/(2.Q+0*PI**2)
  REAL(16),PARAMETER :: V4=1.Q+0/(32.Q+0*PI**2)
  REAL(16),PARAMETER :: C2NC=(NC**2-1.Q+0)/(2.Q+0*NC)

  REAL(16),PARAMETER :: R_4D_TO_3D=1.Q+0
END MODULE CONST_SAVE

MODULE TMU_MOD
  IMPLICIT NONE
  SAVE
  REAL(16) :: T,MU 
  !TEMPERATURE AND CHEMICAL POTENTIAL
  REAL(16) :: JL_UV
END MODULE TMU_MOD

MODULE RHOIR_MOD
  IMPLICIT NONE
  SAVE
  REAL(16) :: ZPHI_IR,RHO_IR
END MODULE RHOIR_MOD

MODULE POLYAKOV_COM
  IMPLICIT NONE
  SAVE
  REAL(16) :: L_COM,LB_COM
END MODULE POLYAKOV_COM

MODULE STRUCFUN_MOD
  IMPLICIT NONE
  SAVE
  INTEGER(2),PARAMETER :: NV=6
  !NV: ORDER OF TYLOR EXPANSION FOR EFFECTIVE POTENTIAL V 0 - NV-1
  INTEGER(2),PARAMETER :: NH=1
  !NH: ORDER OF YUKAWA COUPLING H
  INTEGER(2),PARAMETER :: NZ=4
  !NUMBER OF WAVE FUNCTION RENORMALIZATIONS
  INTEGER(2),PARAMETER :: NCK=2
  INTEGER(2),PARAMETER :: NG=3
  INTEGER(2),PARAMETER :: NH_BG=NV
  INTEGER(2),PARAMETER :: NZ_BG=NH_BG+NH
  INTEGER(2),PARAMETER :: NCK_BG=NZ_BG+NZ
  INTEGER(2),PARAMETER :: NG_BG=NCK_BG+NCK
  INTEGER(2),PARAMETER :: NFLOW=NG_BG+NG
  !NUMBER OF FLOW EQUATIONS
END MODULE STRUCFUN_MOD

MODULE KRANGE_MOD
  IMPLICIT NONE
  SAVE
  REAL(16),PARAMETER :: K_UV=20.Q+3
  REAL(16),PARAMETER :: K_IR= 1.Q-2
  REAL(16),PARAMETER :: T_UV= 0.Q+0
  REAL(16),PARAMETER :: T_IR=LOG(K_IR/K_UV)
END MODULE KRANGE_MOD

MODULE GAUSSMOD
  !GUASS INTEGRAL
  IMPLICIT NONE
  SAVE
  INTEGER(2),PARAMETER :: N_X=64
  REAL(16) :: W_X(N_X),Y_X(N_X)
  REAL(16) :: SQRT_Y_X(N_X)
  INTEGER(2),PARAMETER :: N_CTH=64
  REAL(16) :: W_CTH(N_CTH),Y_CTH(N_CTH) 
END MODULE GAUSSMOD

MODULE Y1W1_MOD
  IMPLICIT NONE
  SAVE
  INTEGER(2),PARAMETER :: NPOINT1=2048
  REAL(16) :: W1(NPOINT1),Y1(NPOINT1) 
END MODULE Y1W1_MOD

MODULE GAPPARA
  USE STRUCFUN_MOD , ONLY : NV
  IMPLICIT NONE
  SAVE
  REAL(16) :: LAM(NV)
  REAL(16) :: JL,KAPPA
  REAL(16) :: C_BAR_S
END MODULE GAPPARA

MODULE POLYAKOV_PER 
  IMPLICIT NONE
  SAVE
  REAL(16) :: APOLYA,CPOLYA,DPOLYA,BPOLYA
END MODULE POLYAKOV_PER

MODULE PHYVAR_MOD
  IMPLICIT NONE
  SAVE
  REAL(16) :: MPION_PHY,MSIGMA_PHY
  REAL(16) :: MPION,MSIGMA
  REAL(16) :: LAMIR_1,LAMIR_2,LAMIR_3,LAMIR_4,LAMIR_5
  REAL(16) :: MF,MFS
  REAL(16) :: ZPHI,ZPSI,ZA,ZPHI_P0
  REAL(16) :: H
  REAL(16) :: G
  REAL(16) :: DELTA_LS
  REAL(16) :: FPI,CL
  REAL(16) :: DRHO1V,DRHO1V_S
END MODULE PHYVAR_MOD

MODULE ODEFUN_COM
  IMPLICIT NONE
  SAVE
  REAL(16) :: FUNSAVE(10)
END MODULE ODEFUN_COM

MODULE ODESAVE_COM
  
  USE STRUCFUN_MOD , ONLY : NFLOW

  IMPLICIT NONE
  SAVE
  INTEGER(2),PARAMETER :: KMAX=3000
  INTEGER(2),PARAMETER :: NFUN=10
  INTEGER(2) :: KOUNT 
  REAL(16) :: DXSAV
  REAL(16) :: XP(KMAX),YP(NFLOW,KMAX),FUNP(NFUN,KMAX) 
END MODULE ODESAVE_COM

MODULE MU0P0_COM
  IMPLICIT NONE
  SAVE
  REAL(16) P0,P0C 
  !TEMPORAL COMPONTENT OF EXTERNAL MOMENTUM
  REAL(16) MU0
END MODULE MU0P0_COM

MODULE ERRORSHOW
  CONTAINS
  SUBROUTINE NRERROR(STRING)
    IMPLICIT NONE
    CHARACTER(LEN=*), INTENT(IN) :: STRING
    WRITE (*,*) 'NRERROR: ',STRING
    STOP 'PROGRAM TERMINATED BY NRERROR'
  END SUBROUTINE NRERROR
END MODULE ERRORSHOW

MODULE FLOWCONFI
  USE Y1W1_MOD
  IMPLICIT NONE
  SAVE
  REAL(16) :: KA(NPOINT1),ETAPSIA(NPOINT1),MF2A(NPOINT1)
  REAL(16) :: MP2A(NPOINT1),ETAPHIA(NPOINT1),MS2A(NPOINT1)
  REAL(16) :: KAPPAA(NPOINT1),HA(NPOINT1),GA(NPOINT1),ZPHIA(NPOINT1)
END MODULE FLOWCONFI

MODULE RHOS_COM
  IMPLICIT NONE
  SAVE
  REAL(16) :: RHOS_I
END MODULE RHOS_COM
