MODULE PHYPINT_MOD
!Rui Wen 2020.10.30
CONTAINS
SUBROUTINE PHYPOINT(YFLOW,VALL)

  USE STRUCFUN_MOD
  USE GAPPARA
  USE PHYVAR_MOD
  USE RHOS_COM
  IMPLICIT NONE
  REAL(16),INTENT(IN)  :: YFLOW(:)
  REAL(16),INTENT(OUT) :: VALL 
  INTEGER,PARAMETER :: NN=1
  REAL(16) :: X(NN)
  LOGICAL CHECK
  EXTERNAL GAPEQ,GAPEQS
  REAL(16) :: SL
  REAL(16) :: MPION2,MSIGMA2

  REAL(16),PARAMETER :: C_S=100.798Q+9
  REAL(16) :: RHOS

  LAM=YFLOW(1:NV)
  H=YFLOW(NH_BG+1)
  ZPHI   =YFLOW(NZ_BG+1)
  ZPSI   =YFLOW(NZ_BG+2)
  ZA     =YFLOW(NZ_BG+3)
  ZPHI_P0=YFLOW(NZ_BG+4)
  JL  =YFLOW(NCK_BG+1)
  SL  =YFLOW(NCK_BG+2)
  G   =YFLOW(NG_BG+1)          

  CL=JL
  FPI=SL

  KAPPA=SL**2/2.Q+0
  X(1)=KAPPA*1.1Q+0
!  CALL NEWT(X, NN, CHECK, GAPEQ)
!  WRITE(*,*)SL,SQRT(2.Q+0*X)
  
  LAMIR_1=LAM(2)
  LAMIR_2=LAM(3)
  LAMIR_3=LAM(4)
  LAMIR_4=LAM(5)
  LAMIR_5=LAM(6)

  MPION2=LAM(2)
  MSIGMA2=LAM(2) + 2.Q+0*KAPPA*LAM(3)

  MPION=SQRT(MPION2)
  MSIGMA=SQRT(MSIGMA2)

  MPION_PHY =MPION *SQRT(ZPHI/ZPHI_P0)
  MSIGMA_PHY=MSIGMA*SQRT(ZPHI/ZPHI_P0)

  MF=H*SL/2.Q+0

  VALL=LAM(1) - JL*SL

  C_BAR_S=C_S/SQRT(ZPHI)
  X(1)=RHOS_I
  CALL NEWT(X, NN, CHECK, GAPEQS)
  RHOS=X(1)
  RHOS_I=RHOS
  DRHO1V_S=C_BAR_S/(2.Q+0*SQRT(RHOS))
  DRHO1V=LAM(2)

  DELTA_LS=SL*(1.Q+0-DRHO1V/DRHO1V_S)/SQRT(ZPHI)
  MFS=H*SQRT(2.Q+0*RHOS)/SQRT(2.Q+0)
!  WRITE(*,*)MFS
END SUBROUTINE PHYPOINT
END MODULE PHYPINT_MOD
