MODULE INITIAL_MOD
! RUI WEN 2020.12.30
CONTAINS
SUBROUTINE INITIAL(YFLOW)
!MAKE THE INITIALIZATION

  USE CONST_SAVE , ONLY : PI
  USE STRUCFUN_MOD
  USE KRANGE_MOD ,ONLY : K_UV
  USE TMU_MOD, ONLY  : JL_UV

  IMPLICIT NONE
  REAL(16),INTENT(OUT) :: YFLOW(:)
  REAL(16),PARAMETER   :: ALPHAS =0.235Q+0
  REAL(16),PARAMETER   :: G      =SQRT(4.Q+0*PI*ALPHAS)
  REAL(16),PARAMETER   :: H      =1.Q+0
  REAL(16),PARAMETER   :: LAMD   =1.Q+4*K_UV**2
  REAL(16),PARAMETER   :: ZPHI   =1.Q+0
  REAL(16),PARAMETER   :: ZPSI   =1.Q+0
  REAL(16),PARAMETER   :: ZA     =1.Q+0
  REAL(16),PARAMETER   :: ZPHI_P0=1.Q+0
  REAL(16) :: LAM(NV)
  REAL(16) :: JL,SL

  JL=JL_UV
  SL =JL/LAMD
  LAM=0.Q+0
  LAM(2)=LAMD
  YFLOW(1:NV)=LAM
  YFLOW(NH_BG+1)=H
  YFLOW(NZ_BG+1)=ZPHI
  YFLOW(NZ_BG+2)=ZPSI
  YFLOW(NZ_BG+3)=ZA
  YFLOW(NZ_BG+4)=ZPHI_P0
  YFLOW(NCK_BG+1)=JL
  YFLOW(NCK_BG+2)=SL
  YFLOW(NG_BG+1:NG_BG+3)=G

END SUBROUTINE INITIAL
END MODULE INITIAL_MOD
