MODULE SELFEQ_MOD
CONTAINS
SUBROUTINE SELFEQ(L_I,LB_I,L,LB,VTOTAL)
!Rui Wen 2021.01.17
  USE TMU_MOD
  USE KRANGE_MOD
  USE STRUCFUN_MOD
  USE POLYAKOV_COM
  USE Y1W1_MOD
  USE POLYAKOV_PER
  USE ODESAVE_COM
  USE FLOWCONFI
  USE RHOIR_MOD

  USE INITIAL_MOD
  USE PHYPINT_MOD
  USE ODE_MOD
  USE INTLIN_MOD
  IMPLICIT NONE
  REAL(16),INTENT(IN) :: L_I,LB_I
  REAL(16),INTENT(OUT) :: L,LB,VTOTAL
  REAL(16) :: L_NEW,LB_NEW,L_OLD,LB_OLD
  REAL(16) :: VALL,VINFI,VGLUE

  !USED FOR LOOPS
  INTEGER(2) :: J
  INTEGER(2),PARAMETER :: JMAX=20
  REAL(16),PARAMETER :: EPSI_ERR=1.Q-10
  REAL(16) :: EPSI_L,EPSI_LB
  LOGICAL :: STOPP

  !USED FOR ODEINT
  REAL(16),PARAMETER :: EPS_ODE=1.Q-7
  REAL(16),PARAMETER :: H1=T_IR/20000.Q+0
  REAL(16),PARAMETER :: HMIN=0.Q+0
  REAL(16) :: YFLOW(NFLOW)

  !USED FOR INTERPOLATION
  REAL(16) :: X_BEF(KMAX)
!  REAL(16),PARAMETER :: BETA=0.8Q+0

  !USED FOR NEWT
  EXTERNAL POLYAKOVEQ
  INTEGER,PARAMETER :: NN=2
  INTEGER II
  REAL(16) X(NN)
  LOGICAL CHECK

  DXSAV=T_IR/10000.Q+0

  CALL POLYAKOVMOD_CAL(T)

  L_NEW=L_I
  LB_NEW=LB_I

  J=0                    
  !START OF LOOPS
  STOPP=.FALSE.
  DO WHILE((.NOT. STOPP).AND.(J < JMAX))
    J=J+1
    WRITE(*,*)'J_LOOP:',J
    L_OLD=L_NEW
    LB_OLD=LB_NEW

    L_COM=L_OLD
    LB_COM=LB_OLD

    CALL INITIAL(YFLOW)
    CALL ODEINT(YFLOW,T_UV,T_IR,EPS_ODE,H1,HMIN)
    CALL PHYPOINT(YFLOW,VALL)
    ZPHI_IR=YFLOW(NZ_BG+1)
    RHO_IR=YFLOW(NCK_BG+2)**2/2.Q+0
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    KA=Y1
    X_BEF=K_UV*EXP(XP)

    CALL INTLIN(X_BEF(1:KOUNT),FUNP(1,1:KOUNT),Y1,ETAPHIA)
    CALL INTLIN(X_BEF(1:KOUNT),FUNP(2,1:KOUNT),Y1,ETAPSIA)
    CALL INTLIN(X_BEF(1:KOUNT),FUNP(3,1:KOUNT),Y1,MF2A)
    CALL INTLIN(X_BEF(1:KOUNT),FUNP(4,1:KOUNT),Y1,MP2A)
    CALL INTLIN(X_BEF(1:KOUNT),FUNP(5,1:KOUNT),Y1,MS2A)
    CALL INTLIN(X_BEF(1:KOUNT),FUNP(6,1:KOUNT),Y1,KAPPAA)
    CALL INTLIN(X_BEF(1:KOUNT),FUNP(7,1:KOUNT),Y1,HA)
    CALL INTLIN(X_BEF(1:KOUNT),FUNP(8,1:KOUNT),Y1,GA)
    CALL INTLIN(X_BEF(1:KOUNT),FUNP(9,1:KOUNT),Y1,ZPHIA)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    X(1)=L_COM
    X(2)=LB_COM
    CALL NEWT(X, NN, CHECK, POLYAKOVEQ)
    L_NEW=X(1)
    LB_NEW=X(2)

    EPSI_L=ABS(L_NEW-L_OLD)/ABS(L_NEW)
    EPSI_LB=ABS(LB_NEW-LB_OLD)/ABS(LB_NEW)

    IF(EPSI_L<EPSI_ERR.AND.EPSI_LB<EPSI_ERR)THEN
      STOPP=.TRUE. 
    END IF

  END DO

  L=L_OLD
  LB=LB_OLD

  VINFI=0.Q+0

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  VGLUE=T**4*(-(APOLYA*L*LB)/2.Q+0 + DPOLYA*L**2*LB**2 + (CPOLYA*(L**3 + LB**3))/2.Q+0 +  &
    BPOLYA*LOG(1 - 6*L*LB - 3*L**2*LB**2 + 4*(L**3 + LB**3)))

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  VTOTAL=VALL+VINFI+VGLUE

END SUBROUTINE SELFEQ
END MODULE SELFEQ_MOD
