PROGRAM EQCD
!Rui Wen 2020.12.30

  USE CONST_SAVE , ONLY : PI
  USE TMU_MOD
  USE PHYVAR_MOD
  USE RHOS_COM
  USE SELFEQ_MOD
  
  IMPLICIT NONE
  REAL(16) :: L,LB 
  !POLYAKOV LOOP
  REAL(16) :: VTOTAL
  REAL(16),PARAMETER :: DT   =  1.Q+0
  REAL(16),PARAMETER :: MUBI =  0.Q+0 
  REAL(16),PARAMETER :: MU_UP=  200.Q+0
  REAL(16),PARAMETER :: MU_DOWN=-MU_UP
  REAL(16) :: MUDELTA,MUB
  REAL(16) :: L_I1,L_I2,LB_I1,LB_I2
  INTEGER(2) :: I,J
  INTEGER(2),PARAMETER :: ITMAX=0
  INTEGER(2),PARAMETER :: MUNUM= 31
  REAL(16),PARAMETER :: MUNUM_R=REAL(MUNUM,KIND=16)
  REAL(16) :: L_SAVE(200)

  RHOS_I=126.Q+0**2/2.Q+0

  CALL GAUSSMOD_CAL()
  CALL Y1W1MOD_CAL()

  !OPEN(unit=11,file='m1.dat')
  !READ(11,*) J
  !CLOSE(11)
  
  L_I1=1.Q-10
  LB_I1=1.Q-10

  L_I2=L_I1
  LB_I2=LB_I1


  MUDELTA=0.Q+00!COS(PI*(REAL(J,KIND=16)-0.5Q+00)/REAL(MUNUM,KIND=16))*(0.5Q+00*(MU_UP-MU_DOWN))+0.5Q+00*(MU_UP+MU_DOWN)

  DO I=1,200
    T=1.Q+00*REAL(I,KIND=16)
    JL_UV=3.6Q+9
    MUB=MUBI+MUDELTA
    MU=MUB/3.Q+0

    CALL SELFEQ(L_I1,LB_I1,L,LB,VTOTAL)
    L_I1=2.Q+0*L-L_I2
    L_I2=L
    LB_I1=2.Q+0*LB-LB_I2
    LB_I2=LB

    WRITE(*,"('I=', I4)")I
    WRITE(*,*)'L =',L
    WRITE(*,*)'LB=',LB
    WRITE(*,"('MUB_MEV=', F15.7, T25, 'T_MEV=', F15.7)")MUB,T
    WRITE(*,*)'MF:',REAL(MF,KIND=8),'MFS',REAL(MFS,KIND=8)
    WRITE(*,*)'MPI_PHY:',MPION_PHY
    WRITE(*,*)'MSG_PHY:',MSIGMA_PHY

    OPEN(UNIT=51,FILE='./BUFFER/VTOTAL.DAT',POSITION='APPEND')
    WRITE(51,*)VTOTAL
    CLOSE(51)
    
  END DO
END PROGRAM EQCD
