SUBROUTINE POLYAKOVEQ(N, X, FVEC)

  USE OMP_LIB

  USE THRNUM_MOD

  USE TMU_MOD
  USE POLYAKOV_PER 
  USE Y1W1_MOD
  USE FLOWCONFI

  USE DTVDIFF_MOD
  IMPLICIT NONE
  INTEGER N
  REAL(16),INTENT(IN) :: X(N)
  REAL(16),INTENT(OUT) :: FVEC(N)
  REAL(16) :: L,LB
  INTEGER(2) :: II,I,INUM

  REAL(16) :: DTVD1L(NPOINT1),DTVD1LB(NPOINT1)
  REAL(16) :: VD1L_1,VD1LB_1,VD1L_4,VD1LB_4,VD1L,VD1LB

  L =X(1)
  LB=X(2)

  !$OMP PARALLEL DO NUM_THREADS(NTHR) PRIVATE(I,INUM)
  DO II=1,NTHR
    DO I=1,(NPOINT1/NTHR)
      INUM=(NPOINT1/NTHR)*(II-1)+I
      CALL DTVDIFF1(KA(INUM),ETAPSIA(INUM),MF2A(INUM),L,LB,DTVD1L(INUM),DTVD1LB(INUM))
      DTVD1L(INUM)=DTVD1L(INUM)/KA(INUM)
      DTVD1LB(INUM)=DTVD1LB(INUM)/KA(INUM)
    END DO
  END DO
  !$OMP END PARALLEL DO

  VD1L_1 =DOT_PRODUCT(W1,DTVD1L )
  VD1LB_1=DOT_PRODUCT(W1,DTVD1LB)

  VD1L_4=((3*CPOLYA*L**2)/2.Q+0 - (APOLYA*LB)/2.Q+0 + 2*DPOLYA*L*LB**2 +       &
    (BPOLYA*(12*L**2 - 6*LB - 6*L*LB**2))/                                     &
     (1 - 6*L*LB - 3*L**2*LB**2 + 4*(L**3 + LB**3)))*T**4

  VD1LB_4=(-(APOLYA*L)/2.Q+0+ 2*DPOLYA*L**2*LB + (3*CPOLYA*LB**2)/2.Q+0 +        &
    (BPOLYA*(-6*L - 6*L**2*LB + 12*LB**2))/                                    &
     (1 - 6*L*LB - 3*L**2*LB**2 + 4*(L**3 + LB**3)))*T**4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  VD1L=VD1L_1+VD1L_4
  VD1LB=VD1LB_1+VD1LB_4

  FVEC(1)=VD1L
  FVEC(2)=VD1LB

END SUBROUTINE POLYAKOVEQ
